name: apache tomcat
run-name: ci part 

on:
  push:
    - master
     
jobs:
  build:
    run on: windows-2019
    
    steps:
      - name: build
        uses: actions/checkout@3.3.0
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: 
        
  
