name: retrigger
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: step1
        run: echo "hi"
  job2:
#     if: failure()
#     needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: check previous build
        run: |
          curl -L -X POST  https://api.github.com/repos/Saralagovind/sarala/actions/runs/${{github.run_id}}/rerun -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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 " -H "X-GitHub-Api-Version: 2022-11-28"
