name: test
on:
  workflow_dispatch:

jobs:
  execute_scripts:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: checkoou code
      uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts
    - name: exect
      run: |
        ssh -o "stricthostkeyChecking=no" root@13.235.79.188 "/root/sarala/hello.sh"
    

